### ISSUE TITLE
Runner pods fail to start with "resource temporarily unavailable"

### ISSUE THREAD

**Issue by jimmyh85** [actions-runner-controller/actions-runner-controller#1146]
**Describe the bug**
We are currently experiencing a weird behavior with our autoscaled runner pods. While trying to deploy autoscaled enterprise runners on our GHES instance we repeatedly see that some of the runner pods fail to start as the registration to GitHub fails with "resource temporarily unavailable".

Further research showed that those runner pods actually do not have a working outbound connection. Does anyone has an idea what might be the root cause of this issue. It looks like a networking issue but I do not get why this only happens to some of the runner pods and then why not all of them. 

I also could not find any issues with resource quotas or similar that might result in this error. 

**Checks**

- [ x ] My actions-runner-controller version (v0.21.1) does support the feature

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [0.21.1]
 - Deployment Method [Helm and Kustomize ]
 - Helm Chart Version [0.16.1]

**Additional context**
Logs from the _diag folder of the runner itself
`
[2022-02-22 16:14:10Z ERR  Runner] System.Net.Http.HttpRequestException: Resource temporarily unavailable (<redacted:443>)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.GetTenantCredential(String githubUrl, String githubToken, String runnerEvent)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[2022-02-22 16:14:10Z ERR  Runner] #####################################################
[2022-02-22 16:14:10Z ERR  Runner] System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2022-02-22 16:14:10Z ERR  Terminal] WRITE ERROR: Resource temporarily unavailable (<redacted:443>)
[2022-02-22 16:14:10Z INFO Listener] Runner execution has finished with return code 1
`

**Comment by jimmyh85** [comment]
Turned out to be a networking issue within our cluster. Not related at all to the Actions Runner Controller!

**Comment by IVData** [comment]
What was the issue here? I'm having a similar problem where my runner pods' network connections are broken.

**Comment by mumoshu** [comment]
@IVData I'd say, generally it's an MTU or a firewall issue! But almost certainly you need to figure it most out yourself.

**Comment by vutruongduc** [comment]
The Docker daemon failed to start because it couldn’t add NAT rules to iptables (bridge driver setup). This happens when iptables is locked by another process, causing the runner to timeout when trying to use Docker.

Fix:
- Disable iptables for dind
- Add restartPolicy: OnFailure to your runner pod template

```
template:
  spec:
    restartPolicy: OnFailure
    containers:
    - name: dind
      image: docker:dind
      args:
        - dockerd
        - --host=unix:///var/run/docker.sock
        - --group=$(DOCKER_GROUP_GID)
        - --iptables=false
        - --bridge=none
      securityContext:
        privileged: true   # needed for DinD
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
```
