### ISSUE TITLE
Can not create python virtual environment because python3-venv package is not installed

### ISSUE THREAD

**Issue by larstiq** [actions-runner-controller/actions-runner-controller#965]
**Describe the bug**

One difference with the GitHub `ubuntu-latest` runner (https://github.com/actions/virtual-environments/blob/2d46e3f4d965927ce242d1fed6d5e92c7ff076c5/images/linux/scripts/installers/python.sh#L17) is the presence of the `python3-venv` package.

This doesn't matter if you're just using the `setup-python` action for your own code, but it does when you're running another action (e.g. https://github.com/akaihola/darker/blob/master/action.yml) that tries to use a Python virtual environment to isolate itself from your code, then you hit the kind of brick wall explained in https://github.com/pypa/build/issues/224:

```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/runner/_work/_actions/akaihola/darker/github-action-v1.3.2-1/.darker-env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

Traceback (most recent call last):
  File "/runner/_work/_actions/akaihola/darker/github-action-v1.3.2-1/action/main.py", line 14, in <module>
    run([sys.executable, "-m", "venv", str(ENV_PATH)], check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'venv', '/runner/_work/_actions/akaihola/darker/github-action-v1.3.2-1/.darker-env']' returned non-zero exit status 1.
```

This is also reproducible by doing: `docker run -it summerwind/actions-runner:latest python -m venv /tmp/boom` or the same in a base Debian/Ubuntu setup.

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

Call `python -m venv /tmp/path-to-venv` inside a `summerwind/actions-runner` image.

**Expected behavior**

Python virtual env creation should work.

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.20.2]
 - Deployment Method [e.g. Helm and Kustomize ]
 - Helm Chart Version [e.g. 0.11.0, if applicable]

**Additional context**

**Comment by bstivers** [comment]
I believe this sort of issue could be solved by following the documentation here: https://github.com/actions-runner-controller/actions-runner-controller#software-installed-in-the-runner-image

**Comment by larstiq** [comment]
I would agree if it wasn't something that breaks basic python functionality, why install any python packages to begin with?

**Comment by mumoshu** [comment]
@larstiq Thanks! As you've kindly described in the `To Reproduce` section, `python -m venv` seems to be the key. For the `darker` action, I spotted it at https://github.com/akaihola/darker/blob/4f2e943e42dbf46c1f338022cac9ab89762bc584/action/main.py#L14. So I believe I now understand the issue.

I basically agree with @bstivers. But I'm still open to suggestions as, honestly, I'm not an experienced python user.

Apparently, there're many occurrences of `python -m venv` in workflow definitions in the wild. 

https://sourcegraph.com/search?q=context:global+python+-m+venv+lang:yaml+file:.github/workflows/.%2B%5C.yaml&patternType=literal

As I remember, our intention to include a standard python environment in our default image was to provide the foundation to run various `setup` actions successfully.

Probably this is a well-known idiom that should work out-of-box in a standard python environment? (=maybe one of `setup` actions may even be using this idiom?

Then I believe we should just install `python3-venv` in our default image.

https://github.com/actions-runner-controller/actions-runner-controller/blob/eefb48ba3f46f6cb2dfb1696ef44950506630b6f/runner/Dockerfile#L31

WDYT @callum-tait-pbx?

**Comment by larstiq** [comment]
> Probably this is a well-known idiom that should work out-of-box in a standard python environment?

Yes, the `venv` module is part of the standard library (https://docs.python.org/3/library/venv.html) and creating these virtual environments is typically the first thing you expect to do with a `python` binary (as also evidenced by the workflow definitions you showed).

The fact that there is a python but  `python -m venv` does not work is hugely surprising to a general audience.

The explanation for this is that Debian/Ubuntu specifically package python in little pieces, it's possible to only use a subset of the standard library (e.g. in resource constrained environments like a boot disk).  If all you do is use the packages provided by the distribution you can live without virtual environments (hence the `python3.9` package `Suggest`ing `python3-venv` but not actually `Depend`ing on it), but note that this is very unusual for development.

Since this is a gotcha for people not intimately familiar with Debian python packaging policies (see also https://gist.github.com/tiran/2dec9e03c6f901814f6d1e8dad09528e#venv-is-broken linked from the https://github.com/pypa/build/issues/224 bug I linked in the initial report) Debian even applies a patch (https://sources.debian.org/patches/python3.9/3.9.2-1/ensurepip-disabled.diff/) to inform the unsuspecting user of what went wrong.


All that taken together I'd advocate for either making sure the expected parts of a standard Python install are present (i.e. install `python3-venv`), or for not having any `python` binary in the image at all so it's clear to people they need to bring it themselves.

**Comment by mumoshu** [comment]
@larstiq Thanks for your confirmation!

@toast-gear I believe we'd better make this enhancement on your runner image.
